# Generated by Django 4.2.3 on 2023-12-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
